/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/build-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuildInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuntimeGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        get: operations["getRuntimeGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-groups/{group_id}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        get: operations["listRuntimeGroupOccurrences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-groups/{group_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acknowledgeRuntimeGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-groups/{group_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveRuntimeGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime-groups/{group_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopenRuntimeGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/applications/{application_id}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get: operations["listReleases"];
        put?: never;
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/applications/{application_id}/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
                release_id: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/applications/{application_id}/releases/{target_id}/runtime-diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
                target_id: components["parameters"]["TargetId"];
            };
            cookie?: never;
        };
        get: operations["getRuntimeDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/webhook-destinations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listWebhookDestinations"];
        put?: never;
        post: operations["createWebhookDestination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/webhook-destinations/{destination_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        get: operations["getWebhookDestination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateWebhookDestination"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/webhook-destinations/{destination_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableWebhookDestination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/webhook-destinations/{destination_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateWebhookSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/webhook-destinations/{destination_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testWebhookDestination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/notification-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listNotificationDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/notification-deliveries/{delivery_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                delivery_id: components["parameters"]["DeliveryId"];
            };
            cookie?: never;
        };
        get: operations["getNotificationDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example not_found */
            error: string;
            /** @example resource not found */
            message: string;
            /** @example 0ec02ed2-8483-4981-893e-bffc535897d7 */
            request_id: string;
        };
        BuildInfo: {
            /** @example 0.1.0 */
            service_version: string;
            /** @example ac23c0b4d042e8d430ea6880f6b66ed1a9d4580a */
            git_commit: string;
            /** @constant */
            api_version: "v1";
            /**
             * Format: int64
             * @example 6
             */
            required_database_migration: number;
        };
        Organization: {
            id: components["schemas"]["Uuid"];
            slug: string;
            name: string;
            created_at: components["schemas"]["Timestamp"];
        };
        Project: {
            id: components["schemas"]["Uuid"];
            slug: string;
            name: string;
            created_at: components["schemas"]["Timestamp"];
            archived_at: components["schemas"]["NullableTimestamp"];
            /** Format: int64 */
            application_count: number;
            /** Format: int64 */
            runtime_group_count: number;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        Application: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            slug: string;
            name: string;
            created_at: components["schemas"]["Timestamp"];
            /** Format: int64 */
            release_count: number;
            /** Format: int64 */
            runtime_group_count: number;
            latest_observed_at: components["schemas"]["NullableTimestamp"];
        };
        ApplicationPage: {
            items: components["schemas"]["Application"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        RuntimeGroup: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            application_id: components["schemas"]["Uuid"];
            cluster_id: components["schemas"]["Uuid"];
            namespace: string;
            workload_kind: string;
            workload_name: string;
            fingerprint_version: number;
            event_kind: string;
            semantic_summary: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "open" | "acknowledged" | "resolved";
            first_seen_at: components["schemas"]["Timestamp"];
            first_seen_event_id: components["schemas"]["Uuid"];
            last_seen_at: components["schemas"]["Timestamp"];
            /** Format: int64 */
            occurrence_count: number;
            representative_event_id: components["schemas"]["Uuid"];
            status_changed_at: components["schemas"]["NullableTimestamp"];
            status_changed_by: components["schemas"]["NullableUuid"];
        };
        RuntimeGroupPage: {
            items: components["schemas"]["RuntimeGroup"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        EventOccurrence: {
            id: components["schemas"]["Uuid"];
            event_id: components["schemas"]["Uuid"];
            observed_at: components["schemas"]["Timestamp"];
            node_name: string;
            namespace: string;
            pod_name: string;
            container_name: string;
            process_command: string;
            event_kind: string;
            payload: {
                [key: string]: unknown;
            };
            release_id: components["schemas"]["NullableUuid"];
            release_version: string | null;
        };
        OccurrencePage: {
            items: components["schemas"]["EventOccurrence"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        FirstSeenNotificationSummary: {
            /** @enum {string} */
            state: "pending" | "not_configured" | "delivering" | "delivered" | "terminally_failed" | "backfill_suppressed";
            /** Format: int64 */
            delivery_count: number;
            /** Format: int64 */
            succeeded_count: number;
            /** Format: int64 */
            failed_count: number;
        };
        RuntimeGroupDetail: components["schemas"]["RuntimeGroup"] & {
            representative_event: components["schemas"]["EventOccurrence"];
            notification: components["schemas"]["FirstSeenNotificationSummary"];
        };
        Release: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            application_id: components["schemas"]["Uuid"];
            version: string;
            description: string | null;
            deployed_at: components["schemas"]["Timestamp"];
            created_at: components["schemas"]["Timestamp"];
        };
        ReleasePage: {
            items: components["schemas"]["Release"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        CreateRelease: {
            version: string;
            description?: string | null;
            deployed_at: components["schemas"]["Timestamp"];
        };
        RuntimeDiffEntry: {
            group_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            classification: "new" | "disappeared" | "unchanged";
            event_kind: string;
            semantic_summary: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            baseline_occurrence_count: number | null;
            baseline_first_seen_at: components["schemas"]["NullableTimestamp"];
            baseline_last_seen_at: components["schemas"]["NullableTimestamp"];
            /** Format: int64 */
            target_occurrence_count: number | null;
            target_first_seen_at: components["schemas"]["NullableTimestamp"];
            target_last_seen_at: components["schemas"]["NullableTimestamp"];
        };
        RuntimeDiff: {
            baseline: components["schemas"]["Release"] | null;
            target: components["schemas"]["Release"];
            items: components["schemas"]["RuntimeDiffEntry"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        WebhookDestination: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            name: string;
            /** Format: uri */
            url: string;
            enabled: boolean;
            deliver_backfill: boolean;
            /** Format: int64 */
            revision: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            disabled_at: components["schemas"]["NullableTimestamp"];
        };
        DestinationWithSecret: components["schemas"]["WebhookDestination"] & {
            secret: string;
        };
        CreateWebhookDestination: {
            name: string;
            /** Format: uri */
            url: string;
            /** @description Defaults to false when omitted. */
            deliver_backfill?: boolean;
        };
        UpdateWebhookDestination: {
            name?: string;
            /** Format: uri */
            url?: string;
            deliver_backfill?: boolean;
            enabled?: boolean;
            /** Format: int64 */
            revision: number;
        };
        DeliverySummary: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            destination_id: components["schemas"]["Uuid"];
            outbox_message_id: components["schemas"]["NullableUuid"];
            origin: string;
            source: string;
            event_name: string;
            status: string;
            available_at: components["schemas"]["Timestamp"];
            /** Format: int32 */
            attempt_count: number;
            /** Format: int32 */
            max_attempts: number;
            last_error_class: string | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            terminal_at: components["schemas"]["NullableTimestamp"];
        };
        DeliveryPage: {
            items: components["schemas"]["DeliverySummary"][];
            next_cursor: components["schemas"]["NullableUuid"];
        };
        DeliveryAttempt: {
            id: components["schemas"]["Uuid"];
            /** Format: int32 */
            attempt_number: number;
            started_at: components["schemas"]["Timestamp"];
            finished_at: components["schemas"]["Timestamp"];
            /** Format: int64 */
            duration_ms: number;
            outcome: string;
            /** Format: int32 */
            http_status: number | null;
            error_class: string | null;
            response_excerpt: string | null;
        };
        DeliveryDetail: components["schemas"]["DeliverySummary"] & {
            attempts: components["schemas"]["DeliveryAttempt"][];
        };
        /** Format: uuid */
        Uuid: string;
        /** Format: uuid */
        NullableUuid: string | null;
        /**
         * Format: date-time
         * @example 2026-08-17T12:00:00Z
         */
        Timestamp: string;
        /** Format: date-time */
        NullableTimestamp: string | null;
    };
    responses: {
        /** @description Build compatibility metadata */
        BuildInfoResponse: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BuildInfo"];
            };
        };
        /** @description Current organization */
        Organization: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Organization"];
            };
        };
        /** @description Project summary */
        Project: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Project"];
            };
        };
        /** @description Project page */
        ProjectPage: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProjectPage"];
            };
        };
        /** @description Application summary */
        Application: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Application"];
            };
        };
        /** @description Application page */
        ApplicationPage: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApplicationPage"];
            };
        };
        /** @description Runtime group page */
        RuntimeGroupPage: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RuntimeGroupPage"];
            };
        };
        /** @description Runtime group */
        RuntimeGroup: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RuntimeGroup"];
            };
        };
        /** @description Runtime group detail */
        RuntimeGroupDetail: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RuntimeGroupDetail"];
            };
        };
        /** @description Runtime group occurrence page */
        OccurrencePage: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OccurrencePage"];
            };
        };
        /** @description Release */
        Release: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Release"];
            };
        };
        /** @description Release page */
        ReleasePage: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ReleasePage"];
            };
        };
        /** @description Runtime behavior diff */
        RuntimeDiff: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RuntimeDiff"];
            };
        };
        /** @description Webhook destination */
        WebhookDestination: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WebhookDestination"];
            };
        };
        /** @description Webhook destinations */
        WebhookDestinationList: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WebhookDestination"][];
            };
        };
        /** @description Webhook destination with one-time secret */
        DestinationWithSecret: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DestinationWithSecret"];
            };
        };
        /** @description Notification delivery summary */
        DeliverySummary: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DeliverySummary"];
            };
        };
        /** @description Notification delivery page */
        DeliveryPage: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DeliveryPage"];
            };
        };
        /** @description Notification delivery detail */
        DeliveryDetail: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DeliveryDetail"];
            };
        };
        /** @description Correlated API error */
        Error: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor scoped to the authenticated collection. */
        Cursor: string;
        Limit: number;
        ProjectId: string;
        ApplicationId: string;
        GroupId: string;
        ReleaseId: string;
        TargetId: string;
        DestinationId: string;
        DeliveryId: string;
    };
    requestBodies: {
        CreateRelease: {
            content: {
                "application/json": components["schemas"]["CreateRelease"];
            };
        };
        CreateWebhookDestination: {
            content: {
                "application/json": components["schemas"]["CreateWebhookDestination"];
            };
        };
        UpdateWebhookDestination: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookDestination"];
            };
        };
    };
    headers: {
        /** @description Correlation identifier for the request. */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBuildInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BuildInfoResponse"];
        };
    };
    getCurrentOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Organization"];
            401: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProjectPage"];
            400: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Project"];
            404: components["responses"]["Error"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ApplicationPage"];
            404: components["responses"]["Error"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Application"];
            404: components["responses"]["Error"];
        };
    };
    listRuntimeGroups: {
        parameters: {
            query: {
                project_id: string;
                application_id: string;
                event_kind?: string;
                status?: "open" | "acknowledged" | "resolved";
                namespace?: string;
                workload_kind?: string;
                workload_name?: string;
                since?: string;
                first_seen_from?: string;
                first_seen_to?: string;
                last_seen_to?: string;
                release_id?: string;
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RuntimeGroupPage"];
        };
    };
    getRuntimeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RuntimeGroupDetail"];
        };
    };
    listRuntimeGroupOccurrences: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OccurrencePage"];
            404: components["responses"]["Error"];
        };
    };
    acknowledgeRuntimeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RuntimeGroup"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    resolveRuntimeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RuntimeGroup"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    reopenRuntimeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RuntimeGroup"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listReleases: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ReleasePage"];
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateRelease"];
        responses: {
            201: components["responses"]["Release"];
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
                release_id: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Release"];
        };
    };
    getRuntimeDiff: {
        parameters: {
            query?: {
                baseline_id?: string;
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                application_id: components["parameters"]["ApplicationId"];
                target_id: components["parameters"]["TargetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RuntimeDiff"];
        };
    };
    listWebhookDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WebhookDestinationList"];
        };
    };
    createWebhookDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateWebhookDestination"];
        responses: {
            201: components["responses"]["DestinationWithSecret"];
        };
    };
    getWebhookDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WebhookDestination"];
        };
    };
    updateWebhookDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateWebhookDestination"];
        responses: {
            200: components["responses"]["WebhookDestination"];
        };
    };
    disableWebhookDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WebhookDestination"];
        };
    };
    rotateWebhookSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DestinationWithSecret"];
        };
    };
    testWebhookDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                destination_id: components["parameters"]["DestinationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeliverySummary"];
        };
    };
    listNotificationDeliveries: {
        parameters: {
            query?: {
                /** @description Opaque cursor scoped to the authenticated collection. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeliveryPage"];
        };
    };
    getNotificationDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                delivery_id: components["parameters"]["DeliveryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeliveryDetail"];
        };
    };
}
